### ISSUE TITLE
npm build之后无法兼容ie8

### ISSUE THREAD

**Issue by happyyi** [zhoulijie/redux-redux-support-ie8#8]
报错提示缺少标识符，不知道该如何操作，我的操作是npm build，然后修改引入的bundle地址，改为dist目录，然后直接跑index.html(无服务器环境)  不知道有没有什么解决方案

**Comment by happyyi** [comment]
chrome下正常，ie8下报错

**Comment by jettangs** [comment]
ie8报错，SCRIPT1028: Expected identifier, string or number
加es5-shim，sham都不行，骗子！

**Comment by zhoulijie** [comment]
https://github.com/xcatliu/react-ie8
https://github.com/ericyang89/react-redux-support-ie8
看看是否对你有帮助
